In [2]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from graphviz import Digraph


a = np.arange(1,11)
tensor = torch.from_numpy(a)
a+=1 #affects the original data and all its references, tensor in this case
print(a,tensor,sep='\n')
a = a+1 # does not affect the references
a,tensor

#image tensors have generally 3 dimensions - height, length, color channels/gradient(RGB)

[ 2  3  4  5  6  7  8  9 10 11]
tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)


(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32))

In [3]:
a1 = torch.arange(1,11).reshape(1,10,1)
a1.shape
#view shares the same underlying data as the orginal while reshape() might create new memory allocations for a new array
#data and shape information are stored separately
a1.size()

torch.Size([1, 10, 1])

In [ ]:
x = torch.arange(1,11)
x.resize((11,1))

In [ ]:
torch.manual_seed(42)
x = torch.randint(1,4,(4,))
print(x)
y = torch.stack([torch.randint(0,i,(2,2)) for i in x],dim=0)
z= torch.stack([torch.randint(0,i,(2,2)) for i in x],dim=1)
y,z

In [ ]:
#requires_grad by default True
#Linear Regression - representing data in terms of linear dependency of a dependent variable 
x1 = torch.randint(1,11,(2,2))
y1 = torch.randint_like(x1,11)
(x1*y1).ndim

In [ ]:
# LLMs in genral - the roadmap
"""
Obtaining data -> Converting/Representing data through numbers -> Understand underlying patterns ->
Get a base model -> Finetunning according to needs -> Final model
""" 
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = torch.randn()

In [117]:
#Pandas
import pandas as pd
x = pd.DataFrame(data=[[1,2,3],[4,5,6],[7,8,9]],
    index = [1,2,3],
    columns=['A','B','C'],
)

# pd.Series([1,2,3,4,4],index=['1','2','3','4','5'])

# x['Y']['2']

# pd.date_range("20041219",periods=10)
x = pd.DataFrame([[1,2],[3.0,4],[5,6]],
                 index=['X','Y','Z'],
                 columns=['A','B'])
x = x.to_csv("x.csv")
file = pd.read_csv("./x.csv",index_col=0)
file.iloc[:3]


#both iloc and loc are row first, col second

A  B
X  1.0  2
Y  3.0  4
Z  5.0  6

In [3]:
import pyaudio

stream = pyaudio.Stream()

C:\Users\Admin\AppData\Local\Temp\ipykernel_14332\3215263311.py:3: DeprecationWarning: Do not instantiate pyaudio.Stream directly. Use pyaudio.PyAudio.open() instead. pyaudio.Stream may change or be removed in the future.
  stream = pyaudio.Stream()


TypeError: PyAudio.Stream.__init__() missing 4 required positional arguments: 'PA_manager', 'rate', 'channels', and 'format'